services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   ENV_VARIABLE: ${ENV_VARIABLE}
      #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    image: ghcr.io/audunbeck/docker-image-test:latest
    expose: 
      - "3000"
    deploy:
      update_config:
        order: start-first

  # Add more containers below (nginx, postgres, etc.)

