services:
  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443" 
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=active.home7023@fastmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  next-app:
    image: ghcr.io/audunbeck/beck-codes:708450b7b6b5a670aedb2d2b30f7259416b448ee
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next-app.rule=Host(`beck.codes`)"
      - "traefik.http.routers.next-app.entrypoints=websecure"
      - "traefik.http.routers.next-app.tls.certresolver=myresolver"
      - "traefik.http.services.next-app.loadbalancer.server.port=3000"

volumes:
  letsencrypt:
